const ADD_PHOTO = 'ADD_PHOTO';
const ADD_ISLOGIN = 'ADD_ISLOGIN';
const EDIT_PROFILE = 'EDIT_PROFILE';
const ADD_USER = 'ADD_USER';
const ADD_USERS_DASHBOARD = 'ADD_USERS_DASHBOARD';
const CLEAN_REDUX = 'CLEAN_REDUX';

export {
  ADD_PHOTO,
  ADD_ISLOGIN,
  EDIT_PROFILE,
  ADD_USER,
  ADD_USERS_DASHBOARD,
  CLEAN_REDUX,
};